Bump version to v1.15.0
ansible/ansible_collections_azure pull request #1109
Opened 2023-03-15 08:53 UTC by Fred-sun

##### SUMMARY

Bump version to v1.15.0

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-03-15 23:21 UTC, akira6592 requested changes

2023-03-15 23:21 UTC, akira6592 commented on CHANGELOG.md
> +## v1.14.0 (2023-03-15)
@Fred-sun Thank you for prepareing for next release! I think the next version should be 1.15.0.

2023-03-16 03:28 UTC, akira6592 approved these changes
@Fred-sun Thank you!

2023-03-16 03:29 UTC, xuzhang3 approved these changes

2023-03-16 03:30 UTC, merged