Suport msgraph sdk in ansible
ansible/ansible_collections_azure pull request #1112
Opened 2023-03-17 09:09 UTC by Fred-sun

##### SUMMARY

Suport msgraph sdk in ansible.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

azure_rm_msuser.py
azure_rm_msuser_info.py
azure_rm_msgroup.py
azure_rm_msgroup_info.py
azure_rm_msserviceprincipal.py
azure_rm_msserviceprincipal_info.py
##### ADDITIONAL INFORMATION

```paste below

```

2023-03-24 09:10 UTC, d2a-pnagel requested changes
Sorry, I only have remarks on the descriptions / comments. Hope it helps.

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/module_utils/azure_rm_common.py
> +        client = GraphClient(credential=credential)
these 2 lines could be combined (`return GraphClient...`)

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msgroup.py
> +            self.log("There is not ad groups {0}".format(str(e)))
There is no group / There are no groups

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msgroup.py
> +                self.log("The ad groups is not exist")
The ad groups do not exist

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msgroup_info.py
> +            - If attribute_name is a collection type it will groups users where attribute_value is in attribute_name.
groups users?

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msgroup_info.py
> +            - If False will return no users.
no users -> no groups?

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msgroup_info.py
> +        - Whether the group is security-enable.
enabled

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msgroup_info.py
> +        - Describe of the ad group.
description

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal.py
> +            - It's service principal's object ID.
It's -> The

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal.py
> +            - Redirects the Web URI,
"Web URI do redirect to." ? When does it redirect?

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal.py
> +            - Redirects the single page application(SPA) URI,
"URI of the Single page application (SPA) to redirect to." ? When does it redirect?

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal.py
> +                    - The authentication response to this URI.
This does not make sense to me.  `redirectUris` = a response?

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal.py
> +                    - The authentication response to this URI.
This does not make sense to me.  `redirectUris` = a response? Do you mean "The URI to redirect to, after authentication."?

2023-03-24 09:10 UTC, d2a-pnagel commented on tests/integration/targets/azure_rm_msserviceprincipal/tasks/main.yml
> +        - https://localhost11
11, not 1?

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msuser_info.py
> +            self.fail("failed to get Microsoft Grpah user info {0}".format(str(e)))
Graph

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msuser_info.py
> +    - name: Get all user in same tenant
Users

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msuser_info.py
> +            - The object id for the user.
"object id" / "object ID" (inconsistent casing)

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal.py
> +                self.log("The Service principal is not exist")
does not exist

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal.py
> +            self.log("There is not service principal {0}".format(str(e)))
not -> no

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal.py
> +            - Redirects the public client/native URI,
same remark as above

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal.py
> +                    - The authentication response to this URI.
same remark as above

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal.py
> +        - Redirects the single page application(SPA) URI,
same remark as above

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal.py
> +        - Redirects the Web URI,
same remark as above

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal_info.py
> +            - It's service principal's object ID.
It's -> The

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal_info.py
> +            - If True, will return all applicatin in tenant.
applications

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal_info.py
> +  - name: get MS sp info by object_id
sp -> service provider

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal_info.py
> +  - name: get all MS sp info
sp -> service provider

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal_info.py
> +  - name: get MS sp info by App ID
sp -> service provider

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal_info.py
> +        -  The collection of application roles that an application may declare.
extra space

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal_info.py
> +        - It's service principal's object ID.
It's -> The

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal_info.py
> +        - Redirects the single page application(SPA) URI,
same remark as earlier on spa/description

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal_info.py
> +        - Redirects the Web URI,
same remark as earlier on web/description

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msserviceprincipal_info.py
> +        - Redirects the public client/native URI.
same remark as earlier

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msuser.py
> +        - The given name for the user.
of the user

2023-03-24 09:10 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msuser.py
> +                self.log("The ad user account not exist")
does not exist

2023-03-24 09:11 UTC, d2a-pnagel requested changes
Sorry, I only have remarks on the descriptions / comments. Hope it helps.

2023-03-24 09:41 UTC, Fred-sun commented on tests/integration/targets/azure_rm_msserviceprincipal/tasks/main.yml
> +        - https://localhost11
just a case, ignore this!

2023-03-24 09:55 UTC, Fred-sun commented
> Sorry, I only have remarks on the descriptions / comments. Hope it helps.

Update! Thanks for your review！

2023-03-24 11:35 UTC, d2a-pnagel approved these changes, later dismissed

2023-03-24 11:35 UTC, d2a-pnagel commented on plugins/modules/azure_rm_msgroup.py
> +            self.log("There is not no group {0}".format(str(e)))
"not no" -> "no"

2023-05-03 14:25 UTC, sboulkour commented
Hello @Fred-sun !
Thx for your work on this, much appreciated :)

I have two question though :
- are resources renamed from ad* to ms* to mark the switch from AD Graph to MS Graph ?
- and in the listed resources I see some missing that would be of use for m personnal use case (azure_rm_adapplication), is it possible to add it to your current PR ?

2023-05-03 23:49 UTC, Fred-sun commented
@sboulkour Yes, Graph RBAC will be migrated to MS Graph and we are adding azure_rm_adapplication and azure_rm_adpass modules! Thanks!

2023-06-12 14:03 UTC, kmj251 commented
Will this PR be merged, and an updated version of the collection released before Azure AD Graph is turned off on June 30, 2023?

2023-07-05 08:41 UTC, Fred-sun commented
Currently, msgraph-core cannot be directly used for aad management, and we are analyzing other ways to solve it. Shut it down for now.

2023-07-05 08:41 UTC, closed without merging

2025-07-09 04:35 UTC, brootware commented
Hello @Fred-sun, came across this thread and found out that this was not merged for Azure b2b collaboration. We ran into a use case to automate this part. May I know if there has been any development/update on this?

2025-07-09 06:26 UTC, Fred-sun commented
@sboulkour Has finished, Please reference https://github.com/ansible-collections/azure/pull/1325