Added force deletion capability to log analytics module and updated requirements.txt
ansible/ansible_collections_azure pull request #273
Opened 2020-09-25 18:58 UTC by next-davidduquehernandez

##### SUMMARY
Added force delete capability introduced on 05/26/2020 update. Updated requirement library 'azure-mgmt-loganalytics' to 1.0.0 and update its method calls.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
azure_rm_loganalyticsworkspace

##### ADDITIONAL INFORMATION
According to [azure documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/delete-workspace) we can force log analytics deletion. This capability allow us to remove log analytics workspace permanently, cause default deletion has a soft-delete behavior.

As requirement was set to 0.2.0 (and this feature was introduced on 1.0.0), this forced me to update requirements and some sdk call methods.

This is my first pull request to an open source project. Please, tell me if I need to do some additional step or modify something in my code. Regards :)

Usage example:

Create log analytics workspace:
```
    - azure_rm_loganalyticsworkspace:
        name: loganalyticsex
        resource_group: rgtest01
        state: present
```

Create output:
```
ok: [localhost] => {
    "changed": false,
    "customer_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/rgtest01/providers/microsoft.operationalinsights/workspaces/loganalyticsex",
    "intelligence_packs": [
        {
            "enabled": false,
            "name": "CapacityPerformance"
        },
        {
            "enabled": false,
            "name": "AzureWebAppsAnalytics"
        },
        {
            "enabled": false,
            "name": "BehaviorAnalyticsInsights"
        },
        {
            "enabled": false,
            "name": "Security"
        },
        {
            "enabled": false,
            "name": "Updates"
        },
        {
            "enabled": false,
            "name": "AntiMalware"
        },
        {
            "enabled": true,
            "name": "LogManagement"
        },
        {
            "enabled": true,
            "name": "AzureResources"
        },
        {
            "enabled": false,
            "name": "ChangeTracking"
        },
        {
            "enabled": false,
            "name": "SQLAssessment"
        },
        {
            "enabled": false,
            "name": "SCOMAssessment"
        },
        {
            "enabled": false,
            "name": "ServiceDesk"
        },
        {
            "enabled": false,
            "name": "SQLAssessmentPlus"
        },
        {
            "enabled": false,
            "name": "ADAssessment"
        },
        {
            "enabled": false,
            "name": "AlertManagement"
        },
        {
            "enabled": false,
            "name": "AzureAutomation"
        },
        {
            "enabled": false,
            "name": "WireData"
        },
        {
            "enabled": false,
            "name": "SiteRecovery"
        },
        {
            "enabled": false,
            "name": "Backup"
        },
        {
            "enabled": false,
            "name": "SurfaceHub"
        },
        {
            "enabled": false,
            "name": "NetworkMonitoring"
        },
        {
            "enabled": false,
            "name": "Containers"
        },
        {
            "enabled": false,
            "name": "ContainerInsights"
        },
        {
            "enabled": false,
            "name": "ServiceMap"
        },
        {
            "enabled": false,
            "name": "AzureNetworking"
        },
        {
            "enabled": false,
            "name": "ADReplication"
        },
        {
            "enabled": false,
            "name": "Office365"
        },
        {
            "enabled": false,
            "name": "CompatibilityAssessment"
        },
        {
            "enabled": false,
            "name": "KeyVault"
        },
        {
            "enabled": false,
            "name": "ServiceFabric"
        },
        {
            "enabled": false,
            "name": "DnsAnalytics"
        },
        {
            "enabled": false,
            "name": "ApplicationInsights"
        },
        {
            "enabled": false,
            "name": "WireData2"
        },
        {
            "enabled": false,
            "name": "WaaSUpdateInsights"
        },
        {
            "enabled": false,
            "name": "AgentHealthAssessment"
        },
        {
            "enabled": false,
            "name": "AzureActivity"
        },
        {
            "enabled": false,
            "name": "HDInsight"
        },
        {
            "enabled": false,
            "name": "HDInsightKafka"
        },
        {
            "enabled": false,
            "name": "HDInsightSpark"
        },
        {
            "enabled": false,
            "name": "HDInsightHadoop"
        },
        {
            "enabled": false,
            "name": "AzureCdnCoreAnalytics"
        },
        {
            "enabled": false,
            "name": "HDInsightStorm"
        },
        {
            "enabled": false,
            "name": "HDInsightInteractiveQuery"
        },
        {
            "enabled": false,
            "name": "VMware"
        },
        {
            "enabled": false,
            "name": "SecurityCenterFree"
        },
        {
            "enabled": false,
            "name": "LogicAppsManagement"
        },
        {
            "enabled": false,
            "name": "LogicAppB2B"
        },
        {
            "enabled": false,
            "name": "AzureSQLAnalytics"
        },
        {
            "enabled": false,
            "name": "KeyVaultAnalytics"
        },
        {
            "enabled": false,
            "name": "AzureNSGAnalytics"
        },
        {
            "enabled": false,
            "name": "AzureAppGatewayAnalytics"
        },
        {
            "enabled": false,
            "name": "DeviceHealthProd"
        },
        {
            "enabled": false,
            "name": "WindowsDefenderATP"
        },
        {
            "enabled": false,
            "name": "WindowsDefenderATPStable"
        },
        {
            "enabled": false,
            "name": "InfrastructureInsights"
        },
        {
            "enabled": false,
            "name": "ProcessInvestigator"
        },
        {
            "enabled": false,
            "name": "Microsoft365Analytics"
        },
        {
            "enabled": false,
            "name": "ASRAnalytics"
        },
        {
            "enabled": false,
            "name": "AzureSentinelPrivatePreview"
        },
        {
            "enabled": false,
            "name": "SecurityInsights"
        },
        {
            "enabled": false,
            "name": "SecurityCenterNetworkTraffic"
        },
        {
            "enabled": false,
            "name": "WindowsFirewall"
        },
        {
            "enabled": false,
            "name": "WindowsEventForwarding"
        },
        {
            "enabled": false,
            "name": "InternalWindowsEvent"
        },
        {
            "enabled": false,
            "name": "CustomizedWindowsEventsFiltering"
        },
        {
            "enabled": false,
            "name": "WEFInternalUat"
        },
        {
            "enabled": false,
            "name": "WEFInternal"
        },
        {
            "enabled": false,
            "name": "WEF_10x"
        },
        {
            "enabled": false,
            "name": "WEF_10xDSRE"
        },
        {
            "enabled": false,
            "name": "DHCPActivity"
        },
        {
            "enabled": false,
            "name": "AzureDataFactoryAnalytics"
        },
        {
            "enabled": false,
            "name": "AzureSecurityOfThings"
        },
        {
            "enabled": false,
            "name": "SQLVulnerabilityAssessment"
        },
        {
            "enabled": false,
            "name": "SQLAdvancedThreatProtection"
        } [...]

2020-09-25 19:33 UTC, imjoseangel commented
Hey @next-davidduquehernandez as a good startup point, it is important to open an issue explaining what do you want to achieve and then link the PR with the comment `Fixes #yourissuenumber`. Document the issue with the requirements to understand what we should expect in the PR.

Thank you!

2020-09-25 19:53 UTC, imjoseangel commented on plugins/modules/azure_rm_loganalyticsworkspace.py
> +        type: bool
`default: no`

2020-09-25 19:54 UTC, imjoseangel commented on plugins/modules/azure_rm_loganalyticsworkspace.py
> +            force=dict(type='bool')
`force=dict(type='bool', default=False)`

2020-09-25 19:58 UTC, imjoseangel requested changes
@next-davidduquehernandez I have added some comments to add a default value to the force option. Nice Job!

2020-09-26 00:01 UTC, next-davidduquehernandez commented
Fixes #274

2020-09-26 00:05 UTC, next-davidduquehernandez commented on plugins/modules/azure_rm_loganalyticsworkspace.py
> +        type: bool
Added default: false better than 'no'

2020-09-26 00:15 UTC, next-davidduquehernandez commented
Thank you for your comments @imjoseangel. I introduced some tests to this PR and fixed 'azure_rm_loganalyticsworkspace_info' too. I has created issue #274 and tried to link with this PR, but I don't know if it's already done.

2020-09-28 10:16 UTC, imjoseangel commented
LGTM

2020-09-29 14:30 UTC, Fred-sun commented
RROR: Found 12 pep8 issue(s) which need to be resolved:
ERROR: plugins/modules/azure_rm_subnet.py:267:161: E501: line too long (261 > 160 characters)
ERROR: plugins/modules/azure_rm_subnet.py:267:262: W291: trailing whitespace
ERROR: plugins/modules/azure_rm_subnet.py:268:1: E128: continuation line under-indented for visual indent
ERROR: plugins/modules/azure_rm_subnet.py:268:161: E501: line too long (256 > 160 characters)
ERROR: plugins/modules/azure_rm_subnet.py:268:257: W291: trailing whitespace
ERROR: plugins/modules/azure_rm_subnet.py:269:1: E128: continuation line under-indented for visual indent
ERROR: plugins/modules/azure_rm_subnet.py:269:161: E501: line too long (271 > 160 characters)
ERROR: plugins/modules/azure_rm_subnet.py:269:272: W291: trailing whitespace
ERROR: plugins/modules/azure_rm_subnet.py:270:1: E128: continuation line under-indented for visual indent
ERROR: plugins/modules/azure_rm_subnet.py:270:161: E501: line too long (271 > 160 characters)
ERROR: plugins/modules/azure_rm_subnet.py:270:272: W291: trailing whitespace
ERROR: plugins/modules/azure_rm_subnet.py:271:1: E128: continuation line under-indented for visual indent
RROR: plugins/modules/azure_rm_subnet.py:0:0: doc-choices-do-not-match-spec: Argument 'serviceName' in argument_spec found in delegations defines choices as (['Microsoft.Web/serverFarms', 'Microsoft.ContainerInstance/containerGroups', 'Microsoft.Netapp/volumes', 'Microsoft.HardwareSecurityModules/dedicatedHSMs', 'Microsoft.ServiceFabricMesh/networks', 'Microsoft.Logic/integrationServiceEnvironments', 'Microsoft.Batch/batchAccounts', 'Microsoft.Sql/managedInstances', 'Microsoft.Web/hostingEnvironments', 'Microsoft.BareMetal/CrayServers', 'Microsoft.BareMetal/MonitoringServers', 'Microsoft.Databricks/workspaces', 'Microsoft.BareMetal/AzureHostedService', 'Microsoft.BareMetal/AzureVMware', 'Microsoft.BareMetal/AzureHPC', 'Microsoft.BareMetal/AzurePaymentHSM', 'Microsoft.StreamAnalytics/streamingJobs', 'Microsoft.DBforPostgreSQL/serversv2', 'Microsoft.AzureCosmosDB/clusters', 'Microsoft.MachineLearningServices/workspaces', 'Microsoft.DBforPostgreSQL/singleServers', 'Microsoft.DBforPostgreSQL/flexibleServers', 'Microsoft.DBforMySQL/serversv2', 'Microsoft.DBforMySQL/flexibleServers', 'Microsoft.ApiManagement/service', 'Microsoft.Synapse/workspaces', 'Microsoft.PowerPlatform/vnetaccesslinks', 'Microsoft.Network/managedResolvers', 'Microsoft.Kusto/clusters']) but documentation defines choices as ([])
ERROR: plugins/modules/azure_rm_subnet.py:0:0: doc-elements-mismatch: Argument 'delegations' in argument_spec specifies elements as dict,but elements is not documented

2020-09-29 15:38 UTC, next-davidduquehernandez commented
> RROR: Found 12 pep8 issue(s) which need to be resolved:
> ERROR: plugins/modules/azure_rm_subnet.py:267:161: E501: line too long (261 > 160 characters)
> ERROR: plugins/modules/azure_rm_subnet.py:267:262: W291: trailing whitespace
> ERROR: plugins/modules/azure_rm_subnet.py:268:1: E128: continuation line under-indented for visual indent
> ERROR: plugins/modules/azure_rm_subnet.py:268:161: E501: line too long (256 > 160 characters)
> ERROR: plugins/modules/azure_rm_subnet.py:268:257: W291: trailing whitespace
> ERROR: plugins/modules/azure_rm_subnet.py:269:1: E128: continuation line under-indented for visual indent
> ERROR: plugins/modules/azure_rm_subnet.py:269:161: E501: line too long (271 > 160 characters)
> ERROR: plugins/modules/azure_rm_subnet.py:269:272: W291: trailing whitespace
> ERROR: plugins/modules/azure_rm_subnet.py:270:1: E128: continuation line under-indented for visual indent
> ERROR: plugins/modules/azure_rm_subnet.py:270:161: E501: line too long (271 > 160 characters)
> ERROR: plugins/modules/azure_rm_subnet.py:270:272: W291: trailing whitespace
> ERROR: plugins/modules/azure_rm_subnet.py:271:1: E128: continuation line under-indented for visual indent
> RROR: plugins/modules/azure_rm_subnet.py:0:0: doc-choices-do-not-match-spec: Argument 'serviceName' in argument_spec found in delegations defines choices as (['Microsoft.Web/serverFarms', 'Microsoft.ContainerInstance/containerGroups', 'Microsoft.Netapp/volumes', 'Microsoft.HardwareSecurityModules/dedicatedHSMs', 'Microsoft.ServiceFabricMesh/networks', 'Microsoft.Logic/integrationServiceEnvironments', 'Microsoft.Batch/batchAccounts', 'Microsoft.Sql/managedInstances', 'Microsoft.Web/hostingEnvironments', 'Microsoft.BareMetal/CrayServers', 'Microsoft.BareMetal/MonitoringServers', 'Microsoft.Databricks/workspaces', 'Microsoft.BareMetal/AzureHostedService', 'Microsoft.BareMetal/AzureVMware', 'Microsoft.BareMetal/AzureHPC', 'Microsoft.BareMetal/AzurePaymentHSM', 'Microsoft.StreamAnalytics/streamingJobs', 'Microsoft.DBforPostgreSQL/serversv2', 'Microsoft.AzureCosmosDB/clusters', 'Microsoft.MachineLearningServices/workspaces', 'Microsoft.DBforPostgreSQL/singleServers', 'Microsoft.DBforPostgreSQL/flexibleServers', 'Microsoft.DBforMySQL/serversv2', 'Microsoft.DBforMySQL/flexibleServers', 'Microsoft.ApiManagement/service', 'Microsoft.Synapse/workspaces', 'Microsoft.PowerPlatform/vnetaccesslinks', 'Microsoft.Network/managedResolvers', 'Microsoft.Kusto/clusters']) but documentation defines choices as ([])
> ERROR: plugins/modules/azure_rm_subnet.py:0:0: doc-elements-mismatch: Argument 'delegations' in argument_spec specifies elements as dict,but elements is not documented

Hi @Fred-sun, thanks for your comment but I think that you was trying to write it to this PR https://github.com/ansible-collections/azure/pull/264 and not mine, cause I'm not modifying plugins/modules/azure_rm_subnet.py, could be?

Regards :)

2020-09-30 01:36 UTC, Fred-sun commented
Sorry,  This is my mistake!

2020-10-22 03:15 UTC, Fred-sun commented
@next-davidduquehernandez Please add line "azure_rm_loganalyticsworkspace" to  pr-pipelines.yml. Thank you very much!

2020-10-22 05:57 UTC, Fred-sun reviewed
Currently, python3 in the pipeline lacks the filter json_query. Cancel it temporarily and change it back after updating the environment. Thank you!

2020-10-22 05:57 UTC, Fred-sun commented on tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
> +      - output.intelligence_packs | json_query('[?name == `Backup`].enabled') | first == true
```suggestion
      #- output.intelligence_packs | json_query('[?name == `Backup`].enabled') | first == true
```

2020-10-22 05:57 UTC, Fred-sun commented on tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
> +      - output.intelligence_packs | json_query('[?name == `Containers`].enabled') | first == true
```suggestion
      #- output.intelligence_packs | json_query('[?name == `Containers`].enabled') | first == true
```

2020-10-22 05:57 UTC, Fred-sun commented on tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
> +      - facts.workspaces[0].intelligence_packs | json_query('[?name == `Backup`].enabled') | first == true
```suggestion
     #- facts.workspaces[0].intelligence_packs | json_query('[?name == `Backup`].enabled') | first == true
```

2020-10-22 05:57 UTC, Fred-sun commented on tests/integration/targets/azure_rm_loganalyticsworkspace/tasks/main.yml
> +      - facts.workspaces[0].intelligence_packs | json_query('[?name == `Containers`].enabled') | first == true
```suggestion
      #- facts.workspaces[0].intelligence_packs | json_query('[?name == `Containers`].enabled') | first == true
```

2020-10-22 17:27 UTC, next-davidduquehernandez commented
Added "azure_rm_loganalyticsworkspace" to pr-pipelines.yml and commented lines with json_query. :)

2020-10-26 06:05 UTC, merged